





repo_url: https://github.com/moyuhualuo/NIT_Book
repo_name: Moyu
edit_uri: edit/main/docs/
site_name: NIT_Book
site_url: https://moyuhualuo.github.io/NIT_Book/

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/library
  features:
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - navigation.footer
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
  hide:
  - footer
  - header
  comments: true
  palette:
    - scheme: default
      primary: lndigo
      accent: deep purple
      toggle:
        icon: material/brightness-6
        name: Light
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-6
        name: Dark

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
      enabled: !ENV [CI, True]
  - git-committers:
      repository: moyuhualuo/mk-docs-material
      branch: main
  - git-authors

plugins:
  - search
  - offline

copyright: Copyright &copy; 2024 NIT_Book




