repo_url: https://github.com/moyuhualuo/NIT_Book
repo_name: Moyu
edit_uri: edit/main/docs/
site_name: NIT_Book
site_url: https://example.com

theme:

  name: material
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/library
  features:
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Light
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-6
        name: Dark

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /cn/
      lang: cn
  homepage: https://github.com


plugins:
  - git-revision-date-localized:
    enable_creation_date: true
    fallback_to_build_date: true
    type: date
    enabled: !ENV [CI, True]
    enable_creation_date: true
    fallback_to_build_date: true
  - git-committers:
      repository: moyuhualuo/mk-docs-material
      branch: main
      branch: main
  - git-authors
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moyuhualuo
      name: My GitHub
    - icon: material/web
      link: https://github.com/moyuhualuo
      name: My web
    - icon: material/email-edit
      link: mailto:<2633699957@qq.com>
      name: Email me

copyright: Copyright &copy; 2024 NIT_Book